version: 2
jobs:
  py3test:
    working_directory: ~/megnet
    docker:
      - image: materialsvirtuallab/circle-ci-pmg-py3:0.0.2
        environment:
          PMG_MAPI_ENDPOINT: https://zola.lbl.gov/rest/v2
    parallelism: 4
    steps:
      - checkout
      - run:
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            if [ ! -d "/root/miniconda3/envs/test_env" ]; then conda create --quiet --yes --name test_env python=3.6; fi
            source activate test_env
            conda install --quiet --yes numpy scipy matplotlib sympy cython
            conda upgrade --quiet --all
            pwd
            ls
            pip install --quiet --ignore-installed -r requirements.txt
      - run:
          command: |
            export PATH=$HOME/miniconda3/bin:$PATH
            export MPLBACKEND=Agg
            source activate test_env
            pip install --quiet -e .
            nosetests --config=nose.cfg --processes=4 --process-timeout=600
          no_output_timeout: 3600

workflows:
  version: 2
  build_and_test:
    jobs:
      - py3test
